"""initial schema

Revision ID: 61ec9f2af05c
Revises: 
Create Date: 2026-03-22 01:24:48.493994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ec9f2af05c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ad_copy', sa.Text(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('analysis_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responses_processed', sa.Integer(), nullable=False),
    sa.Column('new_responses', sa.Integer(), nullable=False),
    sa.Column('themes_detected', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('text_stripped', sa.Text(), nullable=False),
    sa.Column('text_raw_encrypted', sa.Text(), nullable=True),
    sa.Column('response_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'source', 'source_id')
    )
    op.create_table('themes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('response_count', sa.Integer(), nullable=False),
    sa.Column('avg_emotional_intensity', sa.Float(), nullable=True),
    sa.Column('competitor_mention_pct', sa.Float(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('briefs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('theme_id', sa.String(), nullable=False),
    sa.Column('angle_name', sa.String(), nullable=False),
    sa.Column('gap_description', sa.Text(), nullable=False),
    sa.Column('headline_hypothesis', sa.Text(), nullable=False),
    sa.Column('test_recommendation', sa.Text(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('classifications',
    sa.Column('response_id', sa.String(), nullable=False),
    sa.Column('primary_reason', sa.String(), nullable=False),
    sa.Column('competitor_mentioned', sa.Boolean(), nullable=False),
    sa.Column('competitor_name', sa.String(), nullable=True),
    sa.Column('emotional_intensity', sa.Integer(), nullable=False),
    sa.Column('marketing_actionability', sa.String(), nullable=False),
    sa.Column('key_phrases', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('classified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_table('theme_responses',
    sa.Column('theme_id', sa.String(), nullable=False),
    sa.Column('response_id', sa.String(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('theme_id', 'response_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theme_responses')
    op.drop_table('classifications')
    op.drop_table('briefs')
    op.drop_table('themes')
    op.drop_table('responses')
    op.drop_table('integrations')
    op.drop_table('analysis_runs')
    op.drop_table('accounts')
    # ### end Alembic commands ###
